# -*- encoding: utf-8 -*-

=begin
#DaDaPush Public API

#DaDaPush: Real-time Notifications App Send real-time notifications through our API without coding and maintaining your own app for iOS or Android devices.

The version of the OpenAPI document: v1
Contact: contacts@dadapush.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.2

=end

$:.push File.expand_path("../lib", __FILE__)
require "dadapush_client/version"

Gem::Specification.new do |s|
  s.name        = "dadapush_client"
  s.version     = DaDaPushClient::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["DaDaPush.com"]
  s.email       = ["contacts@dadapush.com"]
  s.homepage    = "https://www.dadapush.com"
  s.summary     = "DaDaPush Client For Ruby"
  s.description = "DaDaPush: Real-time Notifications App\nSend real-time notifications through our API without coding and maintaining your own app for iOS or Android devices."
  s.license     = 'Apache-2.0'
  s.required_ruby_version = ">= 1.9"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'
  s.add_runtime_dependency 'json', '~> 2.1', '>= 2.1.0'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'
  s.add_development_dependency 'vcr', '~> 3.0', '>= 3.0.1'
  s.add_development_dependency 'webmock', '~> 1.24', '>= 1.24.3'
  s.add_development_dependency 'autotest', '~> 4.4', '>= 4.4.6'
  s.add_development_dependency 'autotest-rails-pure', '~> 4.1', '>= 4.1.2'
  s.add_development_dependency 'autotest-growl', '~> 0.2', '>= 0.2.16'
  s.add_development_dependency 'autotest-fsevent', '~> 0.2', '>= 0.2.12'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
