=begin
#DaDaPush Public API

#DaDaPush: Real-time Notifications App Send real-time notifications through our API without coding and maintaining your own app for iOS or Android devices.

The version of the OpenAPI document: v1
Contact: contacts@dadapush.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.2

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for DaDaPushClient::MessagePushResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'MessagePushResponse' do
  before do
    # run before each test
    @instance = DaDaPushClient::MessagePushResponse.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MessagePushResponse' do
    it 'should create an instance of MessagePushResponse' do
      expect(@instance).to be_instance_of(DaDaPushClient::MessagePushResponse)
    end
  end
  describe 'test attribute "message_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
