=begin
#DaDaPush Public API

#DaDaPush: Real-time Notifications App Send real-time notifications through our API without coding and maintaining your own app for iOS or Android devices.

The version of the OpenAPI document: v1
Contact: contacts@dadapush.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.2

=end

# Common files
require 'dadapush_client/api_client'
require 'dadapush_client/api_error'
require 'dadapush_client/version'
require 'dadapush_client/configuration'

# Models
require 'dadapush_client/models/action'
require 'dadapush_client/models/message_object'
require 'dadapush_client/models/message_push_request'
require 'dadapush_client/models/message_push_response'
require 'dadapush_client/models/page_response_of_message_object'
require 'dadapush_client/models/result'
require 'dadapush_client/models/result_of_message_object'
require 'dadapush_client/models/result_of_message_push_response'
require 'dadapush_client/models/result_of_page_response_of_message_object'

# APIs
require 'dadapush_client/api/da_da_push_message_api'

module DaDaPushClient
  class << self
    # Customize default settings for the SDK using block.
    #   DaDaPushClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
